drop TABLE IF EXISTS users, requests, items, comments, bookings CASCADE;

create table if not exists users (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(40) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL unique (EMAIL)
);

create table if not exists requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(700) NOT NULL,
    requestor_id BIGINT REFERENCES users (id) ON delete CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

create table if not exists items (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(300) NOT NULL,
    available BOOLEAN NOT NULL,
    owner_id BIGINT REFERENCES users (id) ON delete CASCADE NOT NULL,
    request_id BIGINT REFERENCES requests (id) ON delete CASCADE
);

create table if not exists comments (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    text VARCHAR(500) NOT NULL,
    item_id BIGINT REFERENCES items (id) ON delete CASCADE NOT NULL,
    author_id BIGINT REFERENCES users (id) ON delete CASCADE  NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE
);

create table if not exists bookings (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT REFERENCES items (id) ON delete CASCADE NOT NULL,
    booker_id BIGINT REFERENCES users(id) ON delete CASCADE NOT NULL,
    status VARCHAR(20)
);